### ISSUE TITLE
能不能给个例子呢

### ISSUE THREAD

**Issue by zuosc** [ronggang/PT-Plugin#1]
插件里的说明，感觉太少了点。

最后还是没配置好~

**Comment by zuosc** [comment]
搜索似乎要自己写脚本的。。没配置好


下载的那个配置好了，不过误点一下，整个页面都下载。。好伤。。。。这是什么需求、、、、、

纠结

**Comment by ronggang** [comment]
当初默认配置没传上来。-_-

**Comment by zuosc** [comment]
坐等大佬

**Comment by ronggang** [comment]
@zuosc Wiki已维护，基本操作已做说明，供参考 https://github.com/ronggang/PT-Plugin/wiki

**Comment by zuosc** [comment]
@ronggang  感谢大佬！  周末抽空搞一搞
